### PR TITLE
Add domains: tower.im, aixifan.com, dnstack.com, noc.im

### PR DESCRIPTION
**Pull request by ym**

### CODE REVIEW

**Comment by felixonmars** [comment]
tan14.cn 不需要单独加入，因为所有 `/cn/` 已经被 match 了。其他的看起来没啥问题，谢谢！

**Comment by ym** [comment]
@felixonmars fixed

**Comment by felixonmars** [comment]
Thanks!

**Comment by felixonmars** [comment]
BTW, I have replaced `jsdelivr.net` with `cdn.jsdelivr.net` as other subdomains do not have a CDN as far as I have tested. Please correct me if I am wrong, thanks!

**Comment by ym** [comment]
@felixonmars 
BTW: www.jsdelivr.net is only accessible in China. I don't know is there other subdomains used now except www and cdn.

dig www.jsdelivr.net @8.8.8.8
```
; <<>> DiG 9.10.1-P1 <<>> www.jsdelivr.net @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 46862
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;www.jsdelivr.net.		IN	A

;; AUTHORITY SECTION:
jsdelivr.net.		38	IN	SOA	dns1.p03.nsone.net. hostmaster.nsone.net. 1435436196 43200 7200 1209600 3600

;; Query time: 38 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Aug 13 00:34:27 CST 2015
;; MSG SIZE  rcvd: 107
```

dig www.jsdelivr.net @223.5.5.5
```
; <<>> DiG 9.10.1-P1 <<>> www.jsdelivr.net @223.5.5.5
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7732
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.jsdelivr.net.		IN	A

;; ANSWER SECTION:
www.jsdelivr.net.	3600	IN	A	121.42.163.12

;; Query time: 676 msec
;; SERVER: 223.5.5.5#53(223.5.5.5)
;; WHEN: Thu Aug 13 00:34:37 CST 2015
;; MSG SIZE  rcvd: 50
```

**Comment by felixonmars** [comment]
OK, I've added www.jsdelivr.net too. There are at least `prome-it.jsdelivr.net` and `origin.jsdelivr.net` that are not distributed.

**Pull request merged**
