### PR TITLE
apple: simplify ls.apple.com

### PR DESCRIPTION
**Pull request by wxh06**
https://developer.apple.com/forums/thread/99015

Apple Maps use a variety of `ls.apple.com`'s subdomains.

### CODE REVIEW

**Comment by fernvenue** [comment]
I don't think all its subdomains works great here.

**Comment by wxh06** [comment]
However, Apple Maps does connect to domains that have not been listed here. Should I add them separately? (I'm not sure whether the domain names I captured can cover all services provided by Apple)

**Comment by fernvenue** [comment]
> However, Apple Maps does connect to domains that have not been listed here.

Of course, some other subdomains like `gsp64-ssl.ls.apple.com` also works in Apple Maps, but they don't have CDN in Mainland China, so I believe these subdomains will work better outside the list.

**Comment by wxh06** [comment]
You're right. It's my fault.

I finally figured out that Apple Maps connects to `gspe1-ssl.ls.apple.com` to locate the client's IP region, but its DNS A record does not have any CN IP addresses indeed.

**Pull request closed without merging**
