### PR TITLE
Add DNSPod D+ and order them

### PR DESCRIPTION
**Pull request by soffchen**

### CODE REVIEW

**Comment by felixonmars** [comment]
Thanks, although I am not able to use it :/

```
$ dig +tcp www.baidu.com @119.29.29.29
;; communications error to 119.29.29.29#53: end of file

$ dig www.baidu.com @119.29.29.29

; <<>> DiG 9.10.2-P4 <<>> www.baidu.com @119.29.29.29
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by soffchen** [comment]
https://www.dnspod.cn/httpdns

sigh... closed...

$ dig baidu.com @119.29.29.29

; <<>> DiG 9.8.3-P1 <<>> baidu.com @119.29.29.29
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17345
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;baidu.com.			IN	A

;; ANSWER SECTION:
baidu.com.		421	IN	A	180.149.132.47
baidu.com.		421	IN	A	220.181.57.217
baidu.com.		421	IN	A	123.125.114.144

;; Query time: 36 msec
;; SERVER: 119.29.29.29#53(119.29.29.29)
;; WHEN: Sun Sep  6 23:48:50 2015
;; MSG SIZE  rcvd: 75

$ dig +tcp baidu.com @119.29.29.29

; <<>> DiG 9.8.3-P1 <<>> +tcp baidu.com @119.29.29.29
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14126
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;baidu.com.			IN	A

;; ANSWER SECTION:
baidu.com.		130	IN	A	220.181.57.217
baidu.com.		130	IN	A	123.125.114.144
baidu.com.		130	IN	A	180.149.132.47

;; Query time: 87 msec
;; SERVER: 119.29.29.29#53(119.29.29.29)
;; WHEN: Sun Sep  6 23:48:53 2015
;; MSG SIZE  rcvd: 75

**Comment by soffchen** [comment]
Sorry, it is named 'Public DNS+'.

https://www.dnspod.cn/Products/Public.DNS

**Comment by felixonmars** [comment]
Thanks, I've reported the issue :)

**Pull request merged**
