### PR TITLE
accelerated-domains: add cn.200022.xyz

### PR DESCRIPTION
**Pull request by peeweep**
cn.200022.xyz 是 zhujiwiki.com 的 cname, 只在国内有解析结果。

### CODE REVIEW

**Comment by fernvenue** [comment]
Seems add `200022.xyz` and all its sub domains will be better:

```
~# dig NS 200022.xyz +short
ns1.huaweicloud-dns.org.
ns1.huaweicloud-dns.cn.
ns1.huaweicloud-dns.com.
ns1.huaweicloud-dns.net.
```

**Comment by peeweep** [comment]
目前只发现了这一个子域名，所以我认为写域名/子域名没有什么区别，维护者选喜欢的方式就好。

**Comment by peeweep** [comment]
是否需要我改成 200022.xyz ?

**Comment by fernvenue** [comment]
Yea, as I mentioned above, this domain use `ns1.huaweicloud-dns.cn` as its NS, and `ns1.huaweicloud-dns.cn` is included in [ns-whitelist.txt](https://github.com/felixonmars/dnsmasq-china-list/blob/master/ns-whitelist.txt), so please use `/200022.xyz/` instead of `/cn.200022.xyz/`.

**Comment by felixonmars** [comment]
Thanks!

**Pull request merged**
