### PR TITLE
feat(Makefile): support make clash rules

### PR DESCRIPTION
**Pull request by akiirui**

### CODE REVIEW

**Comment by felixonmars** [comment]
Sorry for the late response. I don't think making them DIRECT would be a good idea as this list only applies to DNS, not the entire routing process. You can feel free to use it this way though, but there are very obvious drawbacks.

**Comment by akiirui** [comment]
> Sorry for the late response. I don't think making them DIRECT would be a good idea as this list only applies to DNS, not the entire routing process. You can feel free to use it this way though, but there are very obvious drawbacks.

Yes, so this PR has been closed.😂

**Comment by LakeishaKowalczyk** [comment]
@akiirui @felixonmars 
Could you please explain why this list is only applicable to DNS? What are the specific drawbacks? Please pardon my curiosity.

**Comment by fernvenue** [comment]
@LakeishaKowalczyk That's because the domains in this list are based on the location of the NS (Name Server), rather than the location of the resolving records. In other words, since the NS of these domains are located in Mainland China, we can use them for DNS resolution to obtain better resolving results, even though **these domains may be resolved to any address**. And for this reason, this list is not suitable for use in other scenarios, as these domains may resolve to anywhere, even though their NS always reside in mainland China.

**Pull request closed without merging**
