### PR TITLE
add domain

### PR DESCRIPTION
**Pull request by pexcn**

### CODE REVIEW

**Comment by felixonmars** [comment]
Doesn't seem to use a CDN or have NS server in China mainland.

**Comment by pexcn** [comment]
Yes, I don't want to use China mainland nameserver, and this domain will always ddns resolved to my home router.

**Comment by pexcn** [comment]
Is there any plan to add a list, that nameservers is not in China mainland, but IP address will always resolve to China?

**Comment by felixonmars** [comment]
I don't think that makes sense. It works pretty fine to use a foreign DNS for this use case.

**Comment by pexcn** [comment]
emmm... this pull request will merge?

**Comment by felixonmars** [comment]
I'm afraid not, since it doesn't fit within the scope of this project. Resolving it should be faster using a foreign DNS too.

**Comment by pexcn** [comment]
Okay, thank you~

**Pull request closed without merging**
