### PR TITLE
Remove duplicated entires.

### PR DESCRIPTION
**Pull request by yukixz**
jsdelivr.net exists at line 19500.
mwcname.com exists at line 23252.
top typo?

### CODE REVIEW

**Comment by wongsyrone** [comment]
https://en.wikipedia.org/wiki/.top_domain

**Comment by yukixz** [comment]
These are many .top entries in conf duplicated with 'top'.
And I can think out the reason considering .top as resolvable.

**Comment by felixonmars** [comment]
The top level domain `top` has NS servers in China mainland. I think the other .top domains are duplicates and should be removed.

**Comment by yukixz** [comment]
`top` is back and duplicaed `*.top` are removed.

**Comment by felixonmars** [comment]
Thanks a lot!

**Pull request merged**
