### PR TITLE
accelerated-domains: add youngmoe.com aplaybox.com

### PR DESCRIPTION
**Pull request by ShiinaRinne**

### CODE REVIEW

**Comment by felixonmars** [comment]
```
youngmoe.com.           3600    IN      NS      stan.ns.cloudflare.com.
youngmoe.com.           3600    IN      NS      zainab.ns.cloudflare.com.
```

Why do you think this domain should be added?

**Review by ShiinaRinne — COMMENTED** [review]
Delete youngmoe.com

**Comment by ShiinaRinne** [comment]
Sorry, it’s my problem. This is my personal domain, which points to a server in Shanghai. I want to set it as a direct connection in v2ray’s geosite.dat, so I found this repo. But because my carelessness, forgot that I had changed it to Cloudflare. 
Now I have deleted it.

**Comment by felixonmars** [comment]
Thanks!

**Pull request merged**
